import json
import subprocess
from pathlib import Path

from agentchange.evidence import extract_model_derived_change_summary
from agentchange.git_analysis import (
    capture_git_snapshot,
    classify_changes,
    ensure_git_baseline,
    write_turn_diff,
)
from agentchange.receipt import render_markdown


def _changes(*paths: str, preexisting: tuple[str, ...] = ()) -> list[dict[str, str]]:
    values = [
        {"path": path, "classification": "New during this turn"}
        for path in paths
    ]
    values.extend(
        {"path": path, "classification": "Pre-existing change"}
        for path in preexisting
    )
    return values


def _block(items: list[dict[str, object]]) -> str:
    return (
        "Implemented the change.\n\n"
        "AGENTCHANGE_CHANGE_SUMMARY_JSON\n"
        + json.dumps({"file_summaries": items})
        + "\nEND_AGENTCHANGE_CHANGE_SUMMARY_JSON"
    )


def test_valid_file_summaries_are_retained_and_labeled():
    result = extract_model_derived_change_summary(
        _block(
            [
                {"path": "web/styles.css", "summary": "Added responsive card styles."},
                {"path": "web/site.js", "summary": "Added pointer tracking."},
            ]
        ),
        _changes("web/styles.css", "web/site.js"),
    )
    assert result.status == "provided"
    assert result.source_label == "Generated by Codex from the observed Git diff."
    assert [item.path for item in result.file_summaries] == ["web/styles.css", "web/site.js"]


def test_invented_and_preexisting_paths_are_discarded():
    result = extract_model_derived_change_summary(
        _block(
            [
                {"path": "changed.py", "summary": "Changed the supported file."},
                {"path": "invented.py", "summary": "Invented change."},
                {"path": "old.py", "summary": "Claimed a pre-existing change."},
            ]
        ),
        _changes("changed.py", preexisting=("old.py",)),
    )
    assert [(item.path, item.summary) for item in result.file_summaries] == [
        ("changed.py", "Changed the supported file.")
    ]
    assert result.discarded_entry_count == 2


def test_malformed_and_missing_summaries_do_not_block_receipt_generation():
    malformed = extract_model_derived_change_summary(
        "AGENTCHANGE_CHANGE_SUMMARY_JSON\n{bad json}\nEND_AGENTCHANGE_CHANGE_SUMMARY_JSON",
        _changes("changed.py"),
    )
    missing = extract_model_derived_change_summary("Implemented the change.", _changes("changed.py"))
    assert malformed.status == "invalid" and not malformed.file_summaries
    assert missing.status == "not_provided" and not missing.file_summaries


def test_summary_paths_are_normalized_but_absolute_and_traversal_paths_are_rejected():
    result = extract_model_derived_change_summary(
        _block(
            [
                {"path": "web\\site.js", "summary": "Normalized a Windows-style separator."},
                {"path": "/home/user/project/web/site.js", "summary": "Absolute path."},
                {"path": "../web/site.js", "summary": "Traversal path."},
                {"path": "other/../web/site.js", "summary": "Embedded traversal path."},
            ]
        ),
        _changes("web/site.js"),
    )
    assert [item.path for item in result.file_summaries] == ["web/site.js"]
    assert result.discarded_entry_count == 3


def test_summary_length_limit_discards_unsupported_description():
    result = extract_model_derived_change_summary(
        _block([{"path": "changed.py", "summary": "x" * 241}]),
        _changes("changed.py"),
    )
    assert result.status == "invalid"
    assert result.discarded_entry_count == 1
    assert not result.file_summaries


def test_summary_requires_plain_text():
    result = extract_model_derived_change_summary(
        _block([{"path": "changed.py", "summary": "Contains a control\u0000character."}]),
        _changes("changed.py"),
    )
    assert result.status == "invalid"
    assert result.discarded_entry_count == 1


def test_four_reported_files_exclude_one_preexisting_file():
    items = [
        {"path": path, "summary": f"Updated {path}."}
        for path in ("one.py", "two.py", "three.py", "old.py")
    ]
    result = extract_model_derived_change_summary(
        _block(items),
        _changes("one.py", "two.py", "three.py", preexisting=("old.py",)),
    )
    assert [item.path for item in result.file_summaries] == ["one.py", "two.py", "three.py"]
    assert result.discarded_entry_count == 1


def test_markdown_separates_observed_paths_from_codex_descriptions():
    receipt = {
        "receipt_id": "acr_summary",
        "risk": {"level": "low", "score": 0, "components": []},
        "repository": {
            "name": "project",
            "branch": "main",
            "turn_changes": [{"path": "web/site.js", "classification": "New during this turn"}],
            "preexisting_change_count": 0,
        },
        "model_derived_change_summary": {
            "status": "provided",
            "source_label": "Generated by Codex from the observed Git diff.",
            "file_summaries": [{"path": "web/site.js", "summary": "Added pointer tracking."}],
        },
        "event_summary": {"model": "gpt-5.6"},
        "turn_change_count": 1,
        "validation": {"summary": "No observed validation commands", "commands": []},
        "slack": {"state": "dry_run"},
        "requested_task": {"value": "Add interaction"},
        "agent_statement": {"value": _block([{"path": "web/site.js", "summary": "Added pointer tracking."}])},
        "observed": {"event_count": 2, "authoritative_validation_count": 0},
        "findings": [],
        "limitations": [],
        "integrity": {},
    }
    markdown = render_markdown(receipt, include_integrity=False)
    assert "## Observed files changed\n\n- `web/site.js`" in markdown
    assert "## Codex summary of observed changes" in markdown
    assert "Generated by Codex from the observed Git diff." in markdown
    assert "- `web/site.js`: Added pointer tracking." in markdown
    assert "AGENTCHANGE_CHANGE_SUMMARY_JSON" not in markdown


def test_markdown_falls_back_when_summary_is_missing():
    receipt = {
        "receipt_id": "acr_summary",
        "risk": {"level": "low", "score": 0, "components": []},
        "repository": {"name": "project", "branch": "main", "turn_changes": [], "preexisting_change_count": 0},
        "model_derived_change_summary": {"status": "not_provided", "file_summaries": []},
        "event_summary": {"model": None},
        "turn_change_count": 0,
        "validation": {"summary": "No observed validation commands", "commands": []},
        "slack": {"state": "dry_run"},
        "requested_task": {"value": None},
        "agent_statement": {"value": None},
        "observed": {"event_count": 0, "authoritative_validation_count": 0},
        "findings": [],
        "limitations": [],
        "integrity": {},
    }
    assert "No file-level summary was provided by Codex." in render_markdown(
        receipt, include_integrity=False
    )


def _git(repo: Path, *arguments: str) -> None:
    subprocess.run(["git", "-C", str(repo), *arguments], check=True, capture_output=True)


def test_turn_diff_contains_only_the_same_turn_delta(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "agentchange@example.invalid")
    _git(repo, "config", "user.name", "AgentChange Test")
    (repo / "existing.txt").write_text("baseline\n", encoding="utf-8")
    _git(repo, "add", "existing.txt")
    _git(repo, "commit", "-qm", "baseline")

    (repo / "existing.txt").write_text("pre-existing\n", encoding="utf-8")
    data = tmp_path / "data"
    baseline_path = ensure_git_baseline(data, "session", "turn", str(repo))
    baseline = json.loads(baseline_path.read_text(encoding="utf-8"))
    (repo / "existing.txt").write_text("pre-existing\nsame-turn\n", encoding="utf-8")
    (repo / "new file.txt").write_text("new\n", encoding="utf-8")

    final = capture_git_snapshot(str(repo))
    attribution = classify_changes(baseline, final)
    diff_path = write_turn_diff(baseline_path.parent, baseline, final, attribution)
    patch = diff_path.read_text(encoding="utf-8")
    assert "+same-turn" in patch
    assert "-baseline" not in patch
    assert "new file.txt" in patch
    assert "+new" in patch
